// <auto-generated />
using MedisyncAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedisyncAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250126172208_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedisyncAPI.models.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Medication1Id")
                        .HasColumnType("int");

                    b.Property<int>("Medication2Id")
                        .HasColumnType("int");

                    b.Property<string>("Pros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Medication1Id");

                    b.HasIndex("Medication2Id");

                    b.ToTable("Interactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cons = "Potential bleeding risk.",
                            InteractionType = "Good",
                            Medication1Id = 1,
                            Medication2Id = 2,
                            Pros = "Improved cardiovascular protection.",
                            Reasoning = "Aspirin helps with blood thinning, and Lisinopril reduces blood pressure, protecting against heart attack.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 2,
                            Cons = "Monitor blood pressure and heart rate closely.",
                            InteractionType = "Good",
                            Medication1Id = 1,
                            Medication2Id = 3,
                            Pros = "Enhanced efficacy in preventing heart attack.",
                            Reasoning = "Aspirin and Metoprolol work synergistically to reduce heart attack risk by thinning blood and reducing pressure.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 3,
                            Cons = "High risk of hypoglycemia.",
                            InteractionType = "Caution",
                            Medication1Id = 5,
                            Medication2Id = 6,
                            Pros = "Effective blood sugar control.",
                            Reasoning = "Both lower blood sugar, but can increase hypoglycemia risk when used together.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 4,
                            Cons = "Monitor liver function due to potential side effects.",
                            InteractionType = "Good",
                            Medication1Id = 9,
                            Medication2Id = 10,
                            Pros = "Improved cholesterol management.",
                            Reasoning = "Atorvastatin inhibits cholesterol production, and Ezetimibe blocks its absorption.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 5,
                            Cons = "Increased risk of side effects like dehydration and liver issues.",
                            InteractionType = "Caution",
                            Medication1Id = 9,
                            Medication2Id = 8,
                            Pros = "Effective in reducing cardiovascular risks.",
                            Reasoning = "Combining SGLT2 inhibitors with Atorvastatin may increase dehydration and liver stress.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 6,
                            Cons = "Monitor for overuse of Albuterol.",
                            InteractionType = "Good",
                            Medication1Id = 13,
                            Medication2Id = 14,
                            Pros = "Effective asthma management.",
                            Reasoning = "Albuterol provides immediate relief, and Fluticasone helps with long-term control of inflammation.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 7,
                            Cons = "Monitor kidney function closely.",
                            InteractionType = "Caution",
                            Medication1Id = 16,
                            Medication2Id = 17,
                            Pros = "Helps manage chronic kidney disease symptoms.",
                            Reasoning = "Diuretics can worsen kidney function, especially when used long-term with Lisinopril.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 8,
                            Cons = "Ensure proper calcium levels to avoid hypercalcemia.",
                            InteractionType = "Good",
                            Medication1Id = 18,
                            Medication2Id = 19,
                            Pros = "Improved bone density.",
                            Reasoning = "Vitamin D aids in calcium absorption, enhancing the effectiveness of Alendronate.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 9,
                            Cons = "Monitor liver function due to Methotrexate.",
                            InteractionType = "Good",
                            Medication1Id = 20,
                            Medication2Id = 19,
                            Pros = "Reduces inflammation while maintaining bone health.",
                            Reasoning = "Vitamin D and Methotrexate are often used together in autoimmune disease treatment to ensure proper bone health.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 10,
                            Cons = "Monitor for potential sedation or dependency.",
                            InteractionType = "Good",
                            Medication1Id = 21,
                            Medication2Id = 22,
                            Pros = "Improved pain management in neuropathic conditions.",
                            Reasoning = "Gabapentin enhances the pain-relieving effect of Tramadol, especially in neuropathic pain.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 11,
                            Cons = "Monitor for overuse of bronchodilators.",
                            InteractionType = "Good",
                            Medication1Id = 23,
                            Medication2Id = 24,
                            Pros = "Better long-term control of COPD symptoms.",
                            Reasoning = "Combining Tiotropium and Formoterol helps maintain open airways, improving breathing in COPD patients.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 12,
                            Cons = "Potential side effects of Amitriptyline (drowsiness, dry mouth).",
                            InteractionType = "Good",
                            Medication1Id = 25,
                            Medication2Id = 26,
                            Pros = "Effective reduction in migraine frequency.",
                            Reasoning = "Botulinum toxin and Amitriptyline work synergistically to prevent and reduce the frequency of chronic migraines.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 13,
                            Cons = "Risk of alkalosis and bloating.",
                            InteractionType = "Caution",
                            Medication1Id = 27,
                            Medication2Id = 28,
                            Pros = "Effective combination for severe GERD.",
                            Reasoning = "Proton Pump Inhibitors decrease acid production, while Antacids neutralize acid; excessive use can cause digestive issues.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 14,
                            Cons = "Monitor for long-term side effects of acid suppression.",
                            InteractionType = "Good",
                            Medication1Id = 29,
                            Medication2Id = 27,
                            Pros = "Enhanced acid control in severe GERD.",
                            Reasoning = "Both H2 blockers and PPIs are effective in treating GERD, often used in combination for more severe cases.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 15,
                            Cons = "Monitor for bradycardia and digoxin toxicity.",
                            InteractionType = "Good",
                            Medication1Id = 30,
                            Medication2Id = 31,
                            Pros = "Improved heart failure management.",
                            Reasoning = "Beta-blockers lower the heart's demand for oxygen, and Digoxin improves contractility, both supporting heart failure patients.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 16,
                            Cons = "Monitor potassium levels closely.",
                            InteractionType = "Good",
                            Medication1Id = 32,
                            Medication2Id = 33,
                            Pros = "Effective fluid management in heart failure.",
                            Reasoning = "Furosemide removes excess fluid, while Spironolactone prevents potassium loss, creating a balanced diuretic effect.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 17,
                            Cons = "High risk of adverse reactions without dose adjustments.",
                            InteractionType = "Caution",
                            Medication1Id = 34,
                            Medication2Id = 35,
                            Pros = "Effective seizure control when managed properly.",
                            Reasoning = "Combining Valproic Acid with Lamotrigine can increase the risk of Lamotrigine toxicity, requiring dose adjustments.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 18,
                            Cons = "Potential for nausea and dyskinesia.",
                            InteractionType = "Good",
                            Medication1Id = 36,
                            Medication2Id = 37,
                            Pros = "Improved Parkinson's symptom management.",
                            Reasoning = "Carbidopa helps Levodopa reach the brain more effectively, enhancing its therapeutic effect in Parkinson's disease.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 19,
                            Cons = "High risk of dopaminergic side effects.",
                            InteractionType = "Caution",
                            Medication1Id = 36,
                            Medication2Id = 38,
                            Pros = "Enhanced symptom control in Parkinson's.",
                            Reasoning = "Combining Pramipexole and Levodopa can increase the risk of dopaminergic side effects like hallucinations or dyskinesia.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 20,
                            Cons = "Monitor for overuse of Albuterol.",
                            InteractionType = "Good",
                            Medication1Id = 39,
                            Medication2Id = 40,
                            Pros = "Effective asthma management.",
                            Reasoning = "Albuterol provides quick relief, while Fluticasone helps with long-term inflammation control.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 21,
                            Cons = "Monitor for dry mouth and irritation.",
                            InteractionType = "Good",
                            Medication1Id = 39,
                            Medication2Id = 41,
                            Pros = "Comprehensive asthma treatment.",
                            Reasoning = "Albuterol provides immediate relief, while Ipratropium prevents future bronchospasms.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 22,
                            Cons = "Risk of corticosteroid-related side effects.",
                            InteractionType = "Good",
                            Medication1Id = 40,
                            Medication2Id = 42,
                            Pros = "Improved control during severe asthma.",
                            Reasoning = "Fluticasone and Prednisone both reduce inflammation, effective during asthma flare-ups.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 23,
                            Cons = "Risk of excessive blood pressure drop.",
                            InteractionType = "Good",
                            Medication1Id = 43,
                            Medication2Id = 44,
                            Pros = "Effective blood pressure control.",
                            Reasoning = "Metoprolol and Amlodipine work synergistically to lower blood pressure and reduce cardiovascular risk.",
                            Severity = "Mild"
                        },
                        new
                        {
                            Id = 24,
                            Cons = "Risk of glycemic imbalance.",
                            InteractionType = "Caution",
                            Medication1Id = 45,
                            Medication2Id = 46,
                            Pros = "Improved lipid and glucose control when monitored.",
                            Reasoning = "Sulfonylureas and Niacin can increase the risk of hyperglycemia in diabetic patients.",
                            Severity = "Moderate"
                        },
                        new
                        {
                            Id = 25,
                            Cons = "High risk of muscle and liver toxicity.",
                            InteractionType = "Caution",
                            Medication1Id = 46,
                            Medication2Id = 47,
                            Pros = "Improved lipid profile management.",
                            Reasoning = "Combining Niacin and Fibrates increases the risk of muscle and liver toxicity.",
                            Severity = "Moderate"
                        });
                });

            modelBuilder.Entity("MedisyncAPI.models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SideEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aspirin",
                            SideEffects = "Nausea, bleeding risk",
                            Use = "Reduces risk of blood clots, preventing heart attacks and strokes."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lisinopril",
                            SideEffects = "Cough, hyperkalemia",
                            Use = "Lowers blood pressure and protects the kidneys."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metoprolol",
                            SideEffects = "Fatigue, dizziness",
                            Use = "Lowers heart rate and blood pressure."
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amlodipine",
                            SideEffects = "Swelling, headache",
                            Use = "Calcium channel blocker that helps lower blood pressure."
                        },
                        new
                        {
                            Id = 5,
                            Name = "Metformin",
                            SideEffects = "Gastrointestinal upset, lactic acidosis (rare)",
                            Use = "Reduces glucose production by the liver and increases insulin sensitivity."
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sulfonylureas (e.g., Glipizide)",
                            SideEffects = "Hypoglycemia, weight gain",
                            Use = "Stimulates insulin production from the pancreas."
                        },
                        new
                        {
                            Id = 7,
                            Name = "Insulin",
                            SideEffects = "Hypoglycemia, weight gain",
                            Use = "Provides insulin to reduce blood glucose."
                        },
                        new
                        {
                            Id = 8,
                            Name = "SGLT2 Inhibitors (e.g., Empagliflozin)",
                            SideEffects = "Dehydration, urinary tract infections",
                            Use = "Reduces glucose reabsorption by the kidneys."
                        },
                        new
                        {
                            Id = 9,
                            Name = "Atorvastatin",
                            SideEffects = "Muscle pain, liver enzyme abnormalities",
                            Use = "Lowers LDL cholesterol and reduces cardiovascular disease risk."
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ezetimibe",
                            SideEffects = "Diarrhea, fatigue",
                            Use = "Reduces cholesterol absorption from the gut."
                        },
                        new
                        {
                            Id = 11,
                            Name = "Niacin",
                            SideEffects = "Flushing, liver toxicity",
                            Use = "Increases HDL (good cholesterol) and lowers LDL and triglycerides."
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fibrate (e.g., Fenofibrate)",
                            SideEffects = "Muscle toxicity, liver enzyme elevation",
                            Use = "Lowers triglycerides and raises HDL cholesterol."
                        },
                        new
                        {
                            Id = 13,
                            Name = "Albuterol",
                            SideEffects = "Tremors, increased heart rate",
                            Use = "Short-acting bronchodilator that opens airways during an attack."
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fluticasone",
                            SideEffects = "Oral thrush, hoarseness",
                            Use = "Inhaled corticosteroid that reduces airway inflammation."
                        },
                        new
                        {
                            Id = 15,
                            Name = "Prednisone",
                            SideEffects = "Weight gain, osteoporosis with long-term use",
                            Use = "Oral corticosteroid for acute exacerbations of asthma."
                        },
                        new
                        {
                            Id = 16,
                            Name = "Lisinopril",
                            SideEffects = "Cough, hyperkalemia",
                            Use = "Protects kidneys, reduces proteinuria, and lowers blood pressure."
                        },
                        new
                        {
                            Id = 17,
                            Name = "Iron Supplements",
                            SideEffects = "Constipation, dark stools",
                            Use = "Replenishes iron levels for red blood cell production."
                        },
                        new
                        {
                            Id = 18,
                            Name = "Alendronate",
                            SideEffects = "Esophageal irritation, jaw osteonecrosis",
                            Use = "Strengthens bones and prevents fractures in osteoporosis."
                        },
                        new
                        {
                            Id = 19,
                            Name = "Vitamin D",
                            SideEffects = "Hypercalcemia, kidney stones",
                            Use = "Enhances calcium absorption and bone health."
                        },
                        new
                        {
                            Id = 20,
                            Name = "Methotrexate",
                            SideEffects = "Bone marrow suppression, liver toxicity",
                            Use = "Immunosuppressant for treating autoimmune conditions like rheumatoid arthritis."
                        },
                        new
                        {
                            Id = 21,
                            Name = "Tramadol",
                            SideEffects = "Drowsiness, dependency risk",
                            Use = "Opioid-like pain reliever for moderate to severe pain."
                        },
                        new
                        {
                            Id = 22,
                            Name = "Gabapentin",
                            SideEffects = "Dizziness, fatigue",
                            Use = "Anticonvulsant used to treat nerve pain."
                        },
                        new
                        {
                            Id = 23,
                            Name = "Tiotropium",
                            SideEffects = "Dry mouth, throat irritation",
                            Use = "Long-acting anticholinergic bronchodilator for COPD."
                        },
                        new
                        {
                            Id = 24,
                            Name = "Formoterol",
                            SideEffects = "Tremors, palpitations",
                            Use = "Long-acting beta-agonist bronchodilator."
                        },
                        new
                        {
                            Id = 25,
                            Name = "Botulinum Toxin (Botox)",
                            SideEffects = "Injection site pain, muscle weakness",
                            Use = "Prevents chronic migraines by blocking pain signals."
                        },
                        new
                        {
                            Id = 26,
                            Name = "Amitriptyline",
                            SideEffects = "Dry mouth, drowsiness",
                            Use = "Tricyclic antidepressant used for migraine prevention."
                        },
                        new
                        {
                            Id = 27,
                            Name = "Proton Pump Inhibitors (e.g., Omeprazole)",
                            SideEffects = "Bloating, constipation",
                            Use = "Reduces stomach acid production to treat GERD."
                        },
                        new
                        {
                            Id = 28,
                            Name = "Antacids (e.g., Calcium Carbonate)",
                            SideEffects = "Constipation, alkalosis",
                            Use = "Neutralizes stomach acid to relieve heartburn."
                        },
                        new
                        {
                            Id = 29,
                            Name = "H2 Receptor Antagonists (e.g., Ranitidine)",
                            SideEffects = "Headache, diarrhea",
                            Use = "Reduces stomach acid production to alleviate heartburn."
                        },
                        new
                        {
                            Id = 30,
                            Name = "Beta-blockers (e.g., Carvedilol)",
                            SideEffects = "Fatigue, bradycardia",
                            Use = "Reduces heart rate and workload, improving heart function."
                        },
                        new
                        {
                            Id = 31,
                            Name = "Digoxin",
                            SideEffects = "Nausea, arrhythmias",
                            Use = "Increases heart contractility and improves symptoms of heart failure."
                        },
                        new
                        {
                            Id = 32,
                            Name = "Furosemide",
                            SideEffects = "Electrolyte imbalance, dehydration",
                            Use = "Loop diuretic that removes excess fluid."
                        },
                        new
                        {
                            Id = 33,
                            Name = "Spironolactone",
                            SideEffects = "Hyperkalemia, gynecomastia",
                            Use = "Diuretic that reduces fluid retention and prevents potassium loss."
                        },
                        new
                        {
                            Id = 34,
                            Name = "Valproic Acid",
                            SideEffects = "Weight gain, liver toxicity",
                            Use = "Anticonvulsant used to control seizures."
                        },
                        new
                        {
                            Id = 35,
                            Name = "Lamotrigine",
                            SideEffects = "Rash, dizziness",
                            Use = "Anticonvulsant used for seizure control."
                        },
                        new
                        {
                            Id = 36,
                            Name = "Levodopa",
                            SideEffects = "Dyskinesia, nausea",
                            Use = "Converts to dopamine in the brain to alleviate symptoms of Parkinson's."
                        },
                        new
                        {
                            Id = 37,
                            Name = "Carbidopa",
                            SideEffects = "Dizziness, nausea",
                            Use = "Inhibits the breakdown of Levodopa, enhancing its effect."
                        },
                        new
                        {
                            Id = 38,
                            Name = "Pramipexole",
                            SideEffects = "Hallucinations, sleepiness",
                            Use = "Dopamine agonist for managing Parkinson's disease."
                        },
                        new
                        {
                            Id = 39,
                            Name = "Albuterol",
                            SideEffects = "Tremors, increased heart rate",
                            Use = "Short-acting bronchodilator for acute asthma relief."
                        },
                        new
                        {
                            Id = 40,
                            Name = "Fluticasone",
                            SideEffects = "Oral thrush, hoarseness",
                            Use = "Inhaled corticosteroid for long-term asthma control."
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ipratropium",
                            SideEffects = "Dry mouth, throat irritation",
                            Use = "Long-acting bronchodilator for asthma prevention."
                        },
                        new
                        {
                            Id = 42,
                            Name = "Prednisone",
                            SideEffects = "Weight gain, osteoporosis",
                            Use = "Oral corticosteroid for severe asthma attacks."
                        },
                        new
                        {
                            Id = 43,
                            Name = "Metoprolol",
                            SideEffects = "Fatigue, dizziness",
                            Use = "Lowers heart rate and blood pressure."
                        },
                        new
                        {
                            Id = 44,
                            Name = "Amlodipine",
                            SideEffects = "Swelling, headache",
                            Use = "Calcium channel blocker that helps lower blood pressure."
                        },
                        new
                        {
                            Id = 45,
                            Name = "Sulfonylureas (e.g., Glipizide)",
                            SideEffects = "Hypoglycemia, weight gain",
                            Use = "Stimulates insulin production from the pancreas."
                        },
                        new
                        {
                            Id = 46,
                            Name = "Niacin",
                            SideEffects = "Flushing, liver toxicity",
                            Use = "Increases HDL (good cholesterol) and lowers LDL and triglycerides."
                        },
                        new
                        {
                            Id = 47,
                            Name = "Fibrate (e.g., Fenofibrate)",
                            SideEffects = "Muscle toxicity, liver enzyme elevation",
                            Use = "Lowers triglycerides and raises HDL cholesterol."
                        });
                });

            modelBuilder.Entity("MedisyncAPI.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$LL0raB/vJRtJjXeo6VEO3uiSYYfSYM3RQdMiJDSDeNiAI5XhqEvkS",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("MedisyncAPI.models.Interaction", b =>
                {
                    b.HasOne("MedisyncAPI.models.Medication", "Medication1")
                        .WithMany("InteractionsAsMed1")
                        .HasForeignKey("Medication1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedisyncAPI.models.Medication", "Medication2")
                        .WithMany("InteractionsAsMed2")
                        .HasForeignKey("Medication2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication1");

                    b.Navigation("Medication2");
                });

            modelBuilder.Entity("MedisyncAPI.models.Medication", b =>
                {
                    b.Navigation("InteractionsAsMed1");

                    b.Navigation("InteractionsAsMed2");
                });
#pragma warning restore 612, 618
        }
    }
}
